[package]
name = "plxc"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.5.0"
clap = { version = "4.5.30", features = ["derive"] }
plx = { path = "../plx"}
chumsky = { version = "1.0.0-alpha.8", features = ["pratt"] }